# TIME UNIT IS IN SECONDS

commands:
  cooldown:
    reset: 300

world:
  resetting time: 30
  unloading time: 600
  size:
    default: 1000
    tyrant: 1500
    nomad: 2500
    brute: 5000

spawnWorld:
  name: "Sandbox"
  location: "-10.5:28.0:909.5:-90.0:1.0"

invites:
  expire time: 300

debug: true