# TIME UNIT IS IN SECONDS

commands:
  cooldown:
    create: 300
    reset: 300

world:
  resetting time: 30
  unloading time: 600
  size:
    default: 1000
    tyrant: 1500
    nomad: 2500
    brute: 5000

spawnWorld: "Sandbox"

invites:
  expire time: 300

bonus chest:
  minimum items: 5
  maximum items: 6
  items:
    1:
      material: WOOD_PICKAXE
    2:
      material: WOOD_AXE
    3:
      material: STONE_PICKAXE
    4:
      material: STONE_AXE
    5:
      material: APPLE
      min: 5
      max: 5
    6:
      material: SAPLING
      min: 2
      max: 2
    7:
      material: GRASS
    8:
      material: STICK
      min: 4
      max: 4
    9:
      material: BUCKET
    10:
      material: GLASS_BOTTLE
    11:
      material: LEATHER_HELMET
    12:
      material: EMPTY_MAP

debug: false