# TIME UNIT IS IN SECONDS

commands:
  cooldown:
    create: 300
    reset: 300

world:
  resetting time: 30
  unloading time: 600
  size:
    default: 500
    tyrant: 750
    nomad: 1000
    brute: 2500

invites:
  expire time: 300

debug: false